name: shopping_app
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1


#-------------------------------PACKAGES-----------------------------------#

dependencies:
  flutter:
    sdk: flutter

  # UTILITY PACKAGES
  http: ^1.5.0
  intl: ^0.20.2
  logger: ^2.6.1
  url_launcher: ^6.3.2
  get_storage: ^2.1.1
  flutter_native_splash: ^2.4.6


  # ICONS
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # STATE MANAGEMENT
  get: ^4.7.2

  # PRODUCT SPECIFIC

  
  




#-------------------------------PACKAGES END-----------------------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^5.0.0





flutter:


# ----------------------------- LOCAL ASSETS ------------------------ #

  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/


# ----------------------------- END LOCAL ASSETS ------------------------ #


# ----------------------------- LOCAL FONTS ------------------------ #

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf

# ----------------------------- END LOCAL FONTS ------------------------ #

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  image: assets/logos/dark_logo.png
  image_dark: assets/logos/light_logo.png
  android_12:
    color: "#FFFFFF"
    color_dark: "#272727"
    image: assets/logos/dark_logo.png
    image_dark: assets/logos/light_logo.png
  web: false
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
